DEF MODIFY_CONTENT(CONTENT):
    """
    MODIFY FILE CONTENT BEFORE SAVING TO NEW FILE.
    FOR NOW, WE'LL MAKE THE TEXT UPPERCASE.
    """
    RETURN CONTENT.UPPER()


DEF MAIN():
    TRY:
        # --- ASK THE USER FOR FILENAME ---
        INPUT_FILE = INPUT("ENTER THE FILENAME TO READ: ").STRIP()

        # --- TRY READING THE FILE ---
        WITH OPEN(INPUT_FILE, "R") AS F:
            CONTENT = F.READ()

        PRINT("\N--- ORIGINAL FILE CONTENT ---")
        PRINT(CONTENT)

        # --- MODIFY THE CONTENT ---
        MODIFIED = MODIFY_CONTENT(CONTENT)

        # --- SAVE TO A NEW FILE ---
        OUTPUT_FILE = "MODIFIED_" + INPUT_FILE
        WITH OPEN(OUTPUT_FILE, "W") AS F:
            F.WRITE(MODIFIED)

        PRINT(F"\N✅ MODIFIED CONTENT HAS BEEN SAVED IN '{OUTPUT_FILE}'")

    EXCEPT FILENOTFOUNDERROR:
        PRINT("❌ ERROR: FILE NOT FOUND. PLEASE CHECK THE NAME AND TRY AGAIN.")
    EXCEPT PERMISSIONERROR:
        PRINT("❌ ERROR: YOU DON’T HAVE PERMISSION TO OPEN THIS FILE.")
    EXCEPT EXCEPTION AS E:
        PRINT(F"❌ UNEXPECTED ERROR: {E}")


IF __NAME__ == "__MAIN__":
    MAIN()

# This line was appended to the modified file.