# FILE READ & WRITE CHALLENGE 🖋️
TRY:
    # ASK THE USER FOR A FILENAME
    FILENAME = INPUT("FILEREADASS.PY: ENTER THE NAME OF THE FILE TO READ/WRITE: ")

    # --- READ A FILE ---
    FILE = OPEN(FILENAME, "R", ENCODING="UTF-8")
    DATA = FILE.READ()
    PRINT("\NORIGINAL CONTENT:\N", DATA)
    FILE.CLOSE()

    # --- MODIFY CONTENT (MAKE UPPERCASE) AND WRITE TO NEW FILE ---
    NEW_FILE = "MODIFIED_" + FILENAME
    FILE = OPEN(NEW_FILE, "W", ENCODING="UTF-8")
    FILE.WRITE(DATA.UPPER())
    FILE.CLOSE()

    # --- APPEND TO THE NEW FILE ---
    FILE = OPEN(NEW_FILE, "A", ENCODING="UTF-8")
    FILE.WRITE("\N# THIS LINE WAS APPENDED TO THE MODIFIED FILE.")
    FILE.CLOSE()

    PRINT(F"\N✅ MODIFIED CONTENT SAVED IN '{NEW_FILE}' WITH AN EXTRA LINE APPENDED!")

# --- ERROR HANDLING LAB 🧪 ---
EXCEPT FILENOTFOUNDERROR:
    PRINT("❌ FILE NOT FOUND. PLEASE CHECK THE NAME AND TRY AGAIN.")
EXCEPT EXCEPTION AS E:
    PRINT("❌ AN ERROR OCCURRED:", E)

# This line was appended to the modified file.